# yaml-language-server: $schema=https://raw.githubusercontent.com/Ledger-Donjon/laserstudio/main/config_schema/config.schema.json
camera:
  enable: true
  label: "Front side Camera"
  type: USB
  refresh_interval_ms: 50
  index: 0
stage:
  enable: true
  label: "Dummy stage"
  refresh_interval_ms: 100
  type: Dummy
  unit_factor: 1000
probes:
  - enable: true
    label: "Dummy Probe"
